### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by 57ar7up** [daveshap/PlainTextWikipedia#4]
```
G:\data\specific\Wikipedia\PlainTextWikipedia-main>python jsonify_wikipedia.py
20210401
Traceback (most recent call last):
  File "G:\data\specific\Wikipedia\PlainTextWikipedia-main\jsonify_wikipedia.py", line 106, in <module>
    main(file)
  File "G:\data\specific\Wikipedia\PlainTextWikipedia-main\jsonify_wikipedia.py", line 83, in main
    with open(archive_dir + file, 'r', encoding='utf-8') as infile:
PermissionError: [Errno 13] Permission denied: 'G:/data/specific/Wikipedia/data/20210401'
```

G:/data/specific/Wikipedia/data/20210401 is existing folder. What's wrong? Running as admin tried too

**Comment by daveshap** [comment]
Looks like you need to add ".xml" or check the filename variable.

**Comment by 57ar7up** [comment]
My problem was in output folder lying inside input folder. This case processed with this code:

104 line: `if 'bz2' in file or os.path.isdir(archive_dir + file):`
